
spring:
  application:
    name: AnimeService
  threads:
    virtual:
      enabled: true
server:
  servlet:
    context-path: /${spring.application.name}
  error:
    include-stacktrace: never
  tomcat:
    threads:
      max: 20

